# Generated by Django 5.0.1 on 2024-01-08 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPeliculas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('año', models.IntegerField()),
                ('temporada', models.CharField(max_length=40)),
            ],
        ),
    ]
