# Generated by Django 5.0.1 on 2024-01-08 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppPeliculas', '0002_serie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serie',
            old_name='temporada',
            new_name='temporadas',
        ),
    ]
