# Generated by Django 5.0.1 on 2024-01-08 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppPeliculas', '0003_rename_temporada_serie_temporadas'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='peliculas',
            new_name='pelicula',
        ),
    ]
