# Generated by Django 5.0.1 on 2024-01-10 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPeliculas', '0004_rename_peliculas_pelicula'),
    ]

    operations = [
        migrations.CreateModel(
            name='musica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('año', models.IntegerField()),
                ('duracion', models.FloatField()),
                ('genero', models.CharField(max_length=40)),
            ],
        ),
    ]
